import type { LocalizedPage } from "./types";


export const platform: LocalizedPage = {
  vi: {
    meta: {
      title: "Nền tảng Aurion",
      description: "Hạ tầng dữ liệu và AI cho bệnh viện: kết nối HIS, kho dữ liệu lâm sàng và các mô hình AI y khoa, triển khai on-premise tại Việt Nam.",
    },
    hero: {
      overline: "Tổng quan nền tảng",
      title: "Hạ tầng dữ liệu và AI cho bệnh viện Việt Nam",
      lead: "Aurion kết nối hệ thống sẵn có của bệnh viện, chuẩn hóa dữ liệu lâm sàng và vận hành AI ngay trên hạ tầng của bệnh viện. Một nền móng chung cho mọi sản phẩm Aurion.",
      visual: "cdr",
    },
    blocks: [
      { type: "logos", heading: "Đang vận hành tại" },
      {
        type: "split",
        id: "context",
        overline: "Aurion Clinical Context",
        status: "live",
        heading: "Mọi dữ liệu lâm sàng, trong cùng một ngữ cảnh",
        body: "AI chỉ hữu ích khi hiểu đúng bối cảnh của bệnh viện. Clinical Context gom dữ liệu từ các hệ thống về một nơi, để mỗi câu trả lời và mỗi quy trình tự động đều dựa trên dữ liệu thật.",
        points: [
          "Đang kết nối với HIS của bệnh viện đối tác",
          "Sẵn sàng tích hợp LIS, PACS, EMR khi bệnh viện cần",
          "Chuẩn hóa dữ liệu về cùng cấu trúc và thuật ngữ",
          "Phân quyền theo đúng vai trò trong bệnh viện",
        ],
        visual: "connectors",
      },
      {
        type: "grid",
        id: "capabilities",
        overline: "Thành phần nền tảng",
        heading: "Mọi thứ AI y khoa cần, trên một nền tảng",
        lead: "Những thành phần đang vận hành tại bệnh viện, cùng các năng lực sẵn sàng triển khai khi bạn cần.",
        items: [
          { id: "connectors", icon: "link", status: "live", title: "Kết nối HIS", desc: "Đồng bộ dữ liệu từ hệ thống thông tin bệnh viện vào nền tảng, liên tục và an toàn." },
          { icon: "circleStack", status: "live", title: "Kho dữ liệu lâm sàng", desc: "Một nguồn dữ liệu thống nhất cho vận hành, AI và nghiên cứu." },
          { id: "deidentification", icon: "eyeSlash", status: "available", title: "Ẩn danh hóa dữ liệu", desc: "Loại bỏ thông tin định danh trước khi dữ liệu được dùng cho nghiên cứu hoặc huấn luyện." },
          { id: "models", icon: "cube", status: "available", title: "Kho mô hình", desc: "Lựa chọn và tinh chỉnh mô hình phù hợp cho từng tác vụ lâm sàng." },
          { id: "ocr", icon: "document", status: "available", title: "OCR y khoa", desc: "Đọc phiếu xét nghiệm, hồ sơ giấy và tài liệu scan thành dữ liệu có cấu trúc." },
          { id: "usage", icon: "adjustments", status: "available", title: "Kiểm soát sử dụng", desc: "Theo dõi và giới hạn cách AI được dùng ở từng khoa phòng." },
        ],
      },
      {
        type: "split",
        id: "cdr",
        overline: "Kho dữ liệu lâm sàng (CDR)",
        status: "live",
        reverse: true,
        heading: "Một nguồn dữ liệu đáng tin cậy",
        body: "Kho dữ liệu lâm sàng lưu trữ tập trung dữ liệu bệnh nhân, xét nghiệm và điều trị theo cấu trúc thống nhất, thay cho những bảng tính và hệ thống rời rạc.",
        points: [
          "Dữ liệu từ HIS được đồng bộ và chuẩn hóa tự động",
          "Trích xuất bộ dữ liệu nghiên cứu trong vài phút",
          "Ẩn danh hóa trước khi dữ liệu rời khỏi kho",
        ],
        visual: "dataset",
      },
      {
        type: "split",
        id: "intelligence",
        overline: "Aurion Intelligence",
        heading: "AI được xây dựng cho y khoa",
        body: "Các mô hình được lựa chọn, tinh chỉnh và giám sát cho từng tác vụ, từ đọc tài liệu scan đến suy luận trên hồ sơ bệnh án. Mọi mô hình đều chạy trên hạ tầng của bệnh viện.",
        points: [
          "OCR đọc phiếu xét nghiệm và hồ sơ giấy",
          "Mô hình liên tục cải thiện với dữ liệu của chính bệnh viện",
          "Giám sát và giới hạn sử dụng theo từng khoa phòng",
        ],
        visual: "ocr",
      },
      {
        type: "stats",
        overline: "Aurion trong con số",
        heading: "Kết quả đo được tại các dự án",
        items: [
          { value: "100%", label: "Dữ liệu lưu trữ tại Việt Nam, trên máy chủ của bệnh viện" },
          { value: "3×", label: "Xử lý mẫu xét nghiệm nhanh hơn" },
          { value: "98%", label: "Độ chính xác trích xuất dữ liệu" },
        ],
      },
      {
        type: "split",
        id: "protect",
        overline: "Aurion Protect",
        reverse: true,
        heading: "Dữ liệu bệnh nhân không bao giờ rời khỏi bệnh viện",
        body: "Aurion được triển khai on-premise, trên máy chủ đặt tại bệnh viện ở Việt Nam. Bảo mật được thiết kế vào nền tảng ngay từ đầu.",
        points: ["Triển khai on-premise tại bệnh viện", "Mã hóa và phân quyền theo vai trò", "Nhật ký truy cập đầy đủ"],
        visual: "onPrem",
      },
      {
        type: "links",
        overline: "Sản phẩm",
        heading: "Được xây dựng trên nền tảng Aurion",
        items: [
          { href: "/product/assistant", icon: "chat", title: "Aurion Assistant", desc: "Trợ lý AI lâm sàng, trả lời kèm nguồn trích dẫn." },
          { href: "/product/operations", icon: "bolt", title: "Aurion Operations", desc: "Lịch phẫu thuật và điều phối bệnh nhân." },
          { href: "/security", icon: "shield", title: "Bảo mật & tuân thủ", desc: "Cách chúng tôi bảo vệ dữ liệu y tế." },
        ],
      },
    ],
  },
  en: {
    meta: {
      title: "The Aurion Platform",
      description: "Data and AI infrastructure for hospitals: HIS integration, a clinical data repository and medical AI models, deployed on-premise in Vietnam.",
    },
    hero: {
      overline: "Platform overview",
      title: "Data and AI infrastructure for Vietnamese hospitals",
      lead: "Aurion connects a hospital's existing systems, standardises clinical data and runs AI on the hospital's own infrastructure. One shared foundation under every Aurion product.",
      visual: "cdr",
    },
    blocks: [
      { type: "logos", heading: "Running at" },
      {
        type: "split",
        id: "context",
        overline: "Aurion Clinical Context",
        status: "live",
        heading: "All clinical data, in one context",
        body: "AI is only useful when it understands the hospital it works in. Clinical Context brings data from the hospital's systems into one place, so every answer and every automated workflow is grounded in real records.",
        points: [
          "Connected to our partner hospital's HIS today",
          "Ready to integrate LIS, PACS and EMR when a hospital needs them",
          "Standardises data into one structure and vocabulary",
          "Respects each role's permissions in the hospital",
        ],
        visual: "connectors",
      },
      {
        type: "grid",
        id: "capabilities",
        overline: "Platform components",
        heading: "Everything medical AI needs, on one platform",
        lead: "Components running in hospitals today, plus capabilities ready to deploy when you need them.",
        items: [
          { id: "connectors", icon: "link", status: "live", title: "HIS integration", desc: "Continuously and securely syncs data from the hospital information system." },
          { icon: "circleStack", status: "live", title: "Clinical data repository", desc: "One consistent source of data for operations, AI and research." },
          { id: "deidentification", icon: "eyeSlash", status: "available", title: "Data de-identification", desc: "Strips identifying information before data is used for research or training." },
          { id: "models", icon: "cube", status: "available", title: "Model hub", desc: "The right model for each clinical task, tuned on the hospital's own data." },
          { id: "ocr", icon: "document", status: "available", title: "Medical OCR", desc: "Turns lab slips, paper records and scans into structured data." },
          { id: "usage", icon: "adjustments", status: "available", title: "Usage controls", desc: "Monitor and limit how AI is used in each department." },
        ],
      },
      {
        type: "split",
        id: "cdr",
        overline: "Clinical data repository (CDR)",
        status: "live",
        reverse: true,
        heading: "One source of clinical truth",
        body: "The clinical data repository keeps patient, lab and treatment data in one consistent structure, replacing scattered spreadsheets and disconnected systems.",
        points: [
          "HIS data is synced and standardised automatically",
          "Research datasets in minutes",
          "De-identified before data leaves the repository",
        ],
        visual: "dataset",
      },
      {
        type: "split",
        id: "intelligence",
        overline: "Aurion Intelligence",
        heading: "AI built for medicine",
        body: "Models chosen, tuned and monitored for each task, from reading scanned documents to reasoning over patient records. Every model runs on the hospital's own infrastructure.",
        points: [
          "OCR reads lab slips and paper records",
          "Models improve continuously on the hospital's own data",
          "Usage monitored and limited per department",
        ],
        visual: "ocr",
      },
      {
        type: "stats",
        overline: "Aurion in numbers",
        heading: "Measured results from our projects",
        items: [
          { value: "100%", label: "Of data stored in Vietnam, on the hospital's own servers" },
          { value: "3×", label: "Faster lab sample processing" },
          { value: "98%", label: "Data extraction accuracy" },
        ],
      },
      {
        type: "split",
        id: "protect",
        overline: "Aurion Protect",
        reverse: true,
        heading: "Patient data never leaves the hospital",
        body: "Aurion is deployed on-premise, on servers inside the hospital in Vietnam. Security is designed into the platform from the start.",
        points: ["On-premise deployment at the hospital", "Encryption and role-based access", "A full access log"],
        visual: "onPrem",
      },
      {
        type: "links",
        overline: "Products",
        heading: "Built on the Aurion platform",
        items: [
          { href: "/product/assistant", icon: "chat", title: "Aurion Assistant", desc: "A clinical AI assistant that cites its sources." },
          { href: "/product/operations", icon: "bolt", title: "Aurion Operations", desc: "Surgery scheduling and patient flow." },
          { href: "/security", icon: "shield", title: "Security & compliance", desc: "How we protect medical data." },
        ],
      },
    ],
  },
};
